# Generated by Django 2.2.5 on 2019-12-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191218_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'en'), ('korean', 'kr')], max_length=7),
        ),
    ]
