# Generated by Django 2.2.5 on 2019-12-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20191218_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='How many poeple will be staying?'),
        ),
    ]
